name: TDD_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^5.0.1
  flutter_bloc: ^6.0.5
  equatable: ^1.2.5
  dartz: ^0.9.1
  connectivity: ^0.4.9+3
  http: ^0.12.2
  shared_preferences: ^0.5.12
  data_connection_checker: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:

  uses-material-design: true

